name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build
        run: ./gradlew build

      - name: Publish Release
        if: startsWith(github.ref, 'refs/tags/v')
        run: MAVEN_TYPE=production ./gradlew publish

      - name: Publish Snapshot
        run: ./gradlew publish

      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/v')
        run: 'curl --fail -X POST -H "Authorization: Bearer ${{ secrets.DEPLOY }}" -F "upload=@$(ls -1 build/libs/merged/*.jar)" https://api.mrmelon54.com/v1/mc-upload/upload/omniplay'
